pages:
  - - name: static
      type: static
      value: "yaib rules"
      # NOTE: see example_command.sh for more information
      # - name: mycommand
      #   type: command
      #   value: "example_command.sh"
      #   icon: "âˆ"
      #   urgency: [25, 50, 80]
      #   urgency_colors: ["#66FF66", "#FFFF44", "#FF6666"]
      #   update_interval: 1s
    - name: music
      type: music
      format: "ğŸ¶: %artist - %title [%time]"
      icon: "ğŸ¶"
    - name: cpu
      type: cpu
      format: "âš›: %usage%"
      urgency: [25, 50, 80]
      urgency_colors: ["#66FF66", "#FFFF44", "#FF6666"]
      icon: "âš›"
    - name: disk
      type: disk
      value: "/"
      format: "ğŸ–´  T: %total, U: %usage"
      urgency: [25, 50, 80]
      urgency_colors: ["#66FF66", "#FFFF44", "#FF6666"]
      icon: "ğŸ–´"
    - name: memory
      type: memory
      format: "ğŸŸ: T: %total, %U: %pct%"
      urgency: [25, 50, 80]
      urgency_colors: ["#66FF66", "#FFFF44", "#FF6666"]
      icon: "ğŸŸ"
    - name: load
      type: load
      format: "ğŸ‹: %1"
      urgency: [25, 50, 80]
      urgency_colors: ["#66FF66", "#FFFF44", "#FF6666"]
      icon: "ğŸ‹"
    - name: time
      type: time
      format: "%a %m/%d %I:%M%P"
